

import java.io.FileReader;
import java.io.FileNotFoundException;

public class NestedTryBlock {

    public static void main(String[] args) {

        try {
            System.out.println("This is the first try block");

            try {
                int a = 20;
                int b = 0;
                int c = a / b; // This will throw ArithmeticException
            } catch (ArithmeticException e) {
                System.out.println("An arithmetic exception has been caught: " + e.getMessage());
            }

            try {
                int[] numbers = {1, 2, 3, 4, 5, 6, 7};
                int number = numbers[10]; // This will throw ArrayIndexOutOfBoundsException
                System.out.println("The number at the 10th position is: " + number);
            } catch (ArrayIndexOutOfBoundsException e) {
                System.out.println("An ArrayIndexOutOfBounds exception has been caught: " + e.getMessage());
            }

            try {
                FileReader reader = new FileReader("file.txt"); // This will throw FileNotFoundException
            } catch (FileNotFoundException e) {
                System.out.println("A FileNotFoundException has been caught: " + e.getMessage());
            } finally {
                System.out.println("This is a finally block");
            }

        } catch (Exception e) {
            System.out.println("An unexpected exception has been caught: " + e.getMessage());
        }
    }
}
